service: analytics
image: jpmagido/plausible_analytics

servers:
  web:
    hosts:
      - 142.93.233.128
    cmd: sh -c "/entrypoint.sh db createdb && /entrypoint.sh db migrate && /entrypoint.sh run"

proxy:
  ssl: true
  host: analytics.jagamio.com
  app_port: 8000
  healthcheck:
    interval: 3
    path: /
    timeout: 3

registry:
  username: jpmagido
  password:
    - KAMAL_REGISTRY_PASSWORD

builder:
  arch: amd64

env:
  clear:
    BASE_URL: "https://analytics.jagamio.com"
    DATABASE_URL: postgres://postgres:<%= ENV.fetch('POSTGRES_PASSWORD') %>@analytics-db:5432/plausible_db
    CLICKHOUSE_DATABASE_URL: http://analytics-events-db:8123/plausible_events_db
  secret:
    - SECRET_KEY_BASE

accessories:
  db:
    image: postgres:16-alpine
    host: 142.93.233.128
    port: "127.0.0.1:5432:5432"
    env:
      secret:
        - POSTGRES_PASSWORD
    directories:
      - db-data:/var/lib/postgresql/data

  events-db:
    image: clickhouse/clickhouse-server:24.12-alpine
    host: 142.93.233.128
    port: "127.0.0.1:8123:8123"
    env:
      clear:
        CLICKHOUSE_SKIP_USER_SETUP: 1
    directories:
      - event-data:/var/lib/clickhouse
      - event-logs:/var/log/clickhouse-server
    files:
      - ./clickhouse/logs.xml:/etc/clickhouse-server/config.d/logs.xml:ro
      - ./clickhouse/ipv4-only.xml:/etc/clickhouse-server/config.d/ipv4-only.xml:ro

